export const surpriseMePrompts = [
  "First Bike Ride",
  "Grandparent's 50th Anniversary",
  "Summer Camp Talent Show",
  "Unexpected Snow Day",
  "Winning the School Spelling Bee",
  "Building a Snow Fort",
  "Catching Fireflies on a Summer Night",
  "First Time Seeing the Ocean",
  "Visiting a Historical Landmark",
  "A Memorable Concert",
  "Learning to Play an Instrument",
  "Baking Cookies with Mom",
  "A Day at the Amusement Park",
  "Hiking to a Waterfall",
  "A Family Picnic in the Park",
  "Watching a Meteor Shower",
  "First Time Flying in a Plane",
  "Visiting a Museum",
  "A Spontaneous Road Trip",
  "Attending a Wedding",
  "Volunteering at a Soup Kitchen",
  "A Surprise Birthday Party",
  "Planting a Garden",
  "A Day at the Zoo",
  "Watching a Play or Musical",
  "Learning a New Language",
  "A Visit to a Farm",
  "Exploring a New City",
  "A Day Spent Fishing",
  "Building a Treehouse",
  "A Sleepover with Friends",
  "Reading a Favorite Book",
  "A Visit to a Science Center",
  "Attending a Sports Game",
  "A Day at the Beach",
  "Visiting a National Park",
  "A Trip to the Mountains",
  "Watching a Sunrise or Sunset",
  "A Day Spent Sailing",
  "Visiting a Botanical Garden",
  "A Trip to the Desert",
  "A Day Spent Kayaking",
  "Visiting a Planetarium",
  "A Trip to the Arctic",
  "A Day Spent Horseback Riding",
  "Visiting a Wildlife Sanctuary",
  "A Trip to the Jungle",
  "A Day Spent Rock Climbing",
  "Visiting an Aquarium",
  "A Trip to the Outback",
  "A Day Spent Surfing",
  "Visiting a Sculpture Garden",
  "A Trip to the Rainforest",
  "A Day Spent Scuba Diving",
  "Visiting a Lighthouse",
  "A Trip to the Coral Reef",
  "A Day Spent Canoeing",
  "Visiting a Historical House",
  "A Trip to the Grand Canyon",
  "A Day Spent Mountain Biking",
  "Visiting a Castle",
  "A Trip to the Amazon",
  "A Day Spent Hot Air Ballooning",
  "Visiting a Vineyard",
  "A Trip to the Alps",
  "A Day Spent White Water Rafting",
  "Visiting a Brewery",
  "A Trip to the Himalayas",
  "A Day Spent Snowboarding",
  "Visiting a Distillery",
  "A Trip to the Sahara",
  "A Day Spent Skiing",
  "Visiting a Coffee Plantation",
  "A Trip to the Serengeti",
  "A Day Spent Dog Sledding",
  "Visiting a Tea Plantation",
  "A Trip to the Galapagos",
  "A Day Spent Ice Skating",
  "Visiting a Spice Market",
  "A Trip to the Nile",
  "A Day Spent Building a Sandcastle",
  "Visiting a Local Market",
  "A Trip to the Great Barrier Reef",
  "A Day Spent Playing in the Snow",
  "Visiting a Local Festival",
  "A Trip to Machu Picchu",
  "A Day Spent Stargazing",
  "Visiting a Local Gallery",
  "A Trip to the Northern Lights",
  "A Day Spent Birdwatching",
  "Visiting a Local Theater",
  "A Trip to the Southern Lights",
  "A Day Spent Playing Board Games",
  "Visiting a Local Bakery",
  "A Trip to the Redwood Forest",
  "A Day Spent Drawing or Painting",
  "Visiting a Local Library",
  "A Trip to the Everglades",
  "A Day Spent Writing a Story",
  "Visiting a Local Park"
]